### ISSUE TITLE
Need Assistance Using XMLCoder!

### ISSUE THREAD

**Issue by Treata11** [CoreOffice/XMLCoder#274]
## A package based on XMLCoder
[MusicXML](https://github.com/dn-m/MusicXML) written by [Jame Bean](https://github.com/jsbean), [Ben Wetherfield](https://github.com/bwetherfield) & [Sihao Lu](https://github.com/DJBen) is heavily base on **XMLCoder** & has been dormant for a couple of years now!
None of the maintainers respond unfortunately ...

### What is the problem?
The package does **not** function & **fails** Tests & probably was left incomplete.
It is based on _MusicXML 3.0_ release & it misses some elements & data types _(4.0 version was added after the project went dormant)_ which I'm currently adding them in a fork that I've created & renamed the package to 
[SwiftMXL](https://github.com/Treata11/SwiftMXL).

Though things are missing & some must be reimplemented, I believe that's not  the only reason that the package is failing. I think that XMLCoder is not properly used as its dependency & that might be contributing to the thrown errors.

## Assistance required 
Since the maintainers of [MusicXML](https://github.com/dn-m/MusicXML) have also contributed to XMLCoder & both packages share similarities, I'd appreciate if anyone could take a look at the crash logs & trace the errs back to its origin. Possibly some of you might even be able to find the problem in a glance.

**Comment by Treata11** [comment]
@fjagerman I appreciate that you took time & investigated the package.
Lemme be frank here :) I don't even know how you faced 17 issues (in XCode 15). You should've faced 6 errors all of which are originated from the implementation of `XMLChoiceDecodingContainer` in `XMLCoder`.

**Comment by fjagerman** [comment]
Hi Treata

Sorry for bothering you with a fix for a problem you don’t have yourself. I changed package.swift (as shown below) because the tests could not access those resources (using Xcode 15.0 and MacOS Sonoma 14.0) 
The resources were introduced with SE-0271. https://github.com/apple/swift-evolution/blob/main/proposals/0271-package-manager-resources.md
p.s. My own project seems to be working fine with  XMLCoder 17.1
Good luck with your project!
 
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SwiftMXL",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "SwiftMXL",
            targets: ["SwiftMXL"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/MaxDesiatov/XMLCoder", from: "0.17.1"),
        .package(url: "https://github.com/jpsim/Yams.git", from: "5.0.6"),
    ],
    targets: [
        .target(
            name: "SwiftMXL",
            dependencies: ["XMLCoder"]
        ),
        .testTarget(
            name: "SwiftMXLTests",
            dependencies: ["SwiftMXL", "Yams"],
            resources: [
                .copy("Complex Types"),
                .copy("LilyPondTests"),
                .copy("ScoreTests"),
            ]),
    ]
)
